### ISSUE TITLE
Doesn't work anymore with Odoo 16?

### ISSUE THREAD

**Issue by Donderda** [pafnow/odoo-web_tree_editable_form_open#1]
Hi there,
we use your plugin and really appreciate it. It works like a charm until Odoo 15. But now - with Odoo 16 - it seems like the events aren't registered properly anymore? 

Could you give me a hint how to fix this?

Kindly Regards

**Comment by pafnow** [comment]
Hi,
In 16.0 Odoo changed completely their frontend to move to a new javascript framework, so I'm not surprised this extension is not working anymore. To be honest, I've not been using for a long long time.
I'll see if I can find a quick upgrade path and keep you posted.

**Comment by pafnow** [comment]
Please have a look to the branch 16.0, and report any issue in a new issue.

**Comment by Donderda** [comment]
Thank you very much! I'll have a look at it :)

**Comment by Donderda** [comment]
Ok, I installed and activated it, but if I double click a row (i.e. the Order Lines of a sale order), nothing happens. Is there any way to make sure that the plugin is loaded correctly? :)
